# Change these first
owner: DoubleYouCash # Your GitHub organization or username, where this repository lives
repo: statuspage # The name of this repository

sites:
  - name: Personal Website
    url: https://www.wyattduber.com
  - name: Resume
    url: https://resume.wyattduber.com
  - name: Wedding
    url: https://wedding.wyattduber.com
  - name: Nextcloud
    url: https://cloud.wyattduber.com
  - name: Gitlab
    url: https://git.wyattduber.com
  - name: iTrakz
    url: https://itrakz.wyattduber.com
  - name: SearXNG
    url: https://search.wyattduber.com
  - name: Memos
    url: https://memos.wyattduber.com
  - name: Paste
    url: https://paste.wyattduber.com
  - name: FilePizza
    url: https://pizza.wyattduber.com
  - name: Plane
    url: https://plane.wyattduber.com
  - name: Homepage
    url: https://home.wyattduber.com
  - name: Repo
    url: https://repo.wyattduber.com
  - name: AMP
    url: https://server.wyattduber.com
  - name: EMP AMP
    url: https://server.endofthemapparty.com

assignees:
  - DoubleYouCash

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.wyattduber.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: "Status Page: Wyatt Duberstein"
  introTitle: "Wyatt Duberstein's Status Page"
  introMessage: This website checks my various websites and verifies that they are up and running. If there are any downtime issues, email me at [wyattduberstein@gmail.com](mailto:wyattduberstein@gmail.com). **Powered by [Upptime](https://github.com/upptime/upptime)**. 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
